### ISSUE TITLE
codespace fails to launch

### ISSUE THREAD

**Issue by karlrissland** [Azure/reddog-code#35]
Click on the new codespace button
![image](https://user-images.githubusercontent.com/9871029/144093492-85b0a3bd-2f31-49ce-91dd-bec5b9f5d993.png)

Wait for a little while and receive the following error
![image](https://user-images.githubusercontent.com/9871029/144093343-a05db9e0-5bd5-4b52-b16c-774d1278b617.png)

**Comment by lgmorand** [comment]
just tried, few seconds ago, works like a charm.
I used the codespace shortcut "."

**Comment by lynn-orrell** [comment]
@karlrissland, can you please give this another try? We've made changes recently and it should now work. If you can verify, I'll close out this issue.

**Comment by alicejgibbons** [comment]
This should be fixed now! Closing :)
